export const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands [Malvinas]",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea",
  "Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United States Minor Outlying Islands",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
  "Afghanistan",
  "Albanie",
  "Algérie",
  "Samoa américaines",
  "Andorre",
  "Angola",
  "Anguilla",
  "Antarctique",
  "Antigua-et-Barbuda",
  "Argentine",
  "Arménie",
  "Aruba",
  "Australie",
  "L'Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Biélorussie",
  "Belgique",
  "Bélize",
  "Bénin",
  "Bermudes",
  "Bhoutan",
  "Bolivie",
  "Bonaire",
  "Bosnie Herzégovine",
  "Botswana",
  "Île Bouvet",
  "Brésil",
  "Territoire britannique de l'océan Indien",
  "Brunei Darussalam",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cap-Vert",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Îles Caïmans",
  "République centrafricaine",
  "Tchad",
  "Chili",
  "Chine",
  "L'île de noël",
  "Iles Cocos",
  "Colombie",
  "Comores",
  " Congo ",
  "Les Îles Cook",
  "Costa Rica",
  "Croatie",
  "Cuba",
  "Curacao",
  "Chypre",
  "Tchéquie",
  "Côte d'Ivoire",
  "Danemark",
  "Djibouti",
  "Dominique",
  "République Dominicaine",
  "Equateur",
  "Egypte",
  "Le Salvador",
  "Guinée Équatoriale",
  "Erythrée",
  "Estonie",
  "Eswatini",
  "Ethiopie",
  "Îles Falkland [Malouines]",
  "Îles Féroé",
  "Fidji",
  "Finlande",
  "France",
  "Guyane Française",
  "Polynésie française",
  "Terres Australes Françaises",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Allemagne",
  "Ghana",
  "Gibraltar",
  "Grèce",
  "Groenland",
  "Grenade",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernesey",
  "Guinée",
  "Guinée-Bissau",
  "Guyane",
  "Haïti",
  "Île Heard et îles McDonald",
  "Saint-Siège",
  "Honduras",
  "Hong Kong",
  "Hongrie",
  "Islande",
  "Inde",
  "Indonésie",
  "L'Iran",
  "Irak",
  "Irlande",
  "Île de Man",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Corée",
  "Corée",
  "Koweit",
  "Kirghizistan",
  "République démocratique populaire lao",
  "Lettonie",
  "Liban",
  "Lesotho",
  "Libéria",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaisie",
  "Maldives",
  " Mali ",
  "Malte",
  "Iles Marshall",
  " Martinique ",
  "Mauritanie",
  "Maurice",
  "Mayotte",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Montserrat",
  "Maroc",
  "Mozambique",
  "Birmanie",
  "Namibie",
  "Nauru",
  "Népal",
  "Pays-Bas",
  "Nouvelle Calédonie",
  "Nouvelle-Zélande",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niué",
  "L'ile de Norfolk",
  "Îles Mariannes du Nord",
  "Norvège",
  "Oman",
  "Pakistan",
  "Palaos",
  "Palestine, État de",
  "Panama",
  "Papouasie Nouvelle Guinée",
  "Paraguay",
  "Pérou",
  "Philippines",
  "Pitcairn",
  "Pologne",
  "Le Portugal",
  "Porto Rico",
  "Qatar",
  "République de Macédoine du Nord",
  "Roumanie",
  "Fédération Russe",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Sainte Hélène, Ascension et Tristan da Cunha",
  "Saint-Christophe-et-Niévès",
  "Sainte-Lucie",
  "Saint Martin (partie française)",
  "Saint-Pierre-et-Miquelon",
  "Saint-Vincent-et-les-Grenadines",
  "Samoa",
  "Saint Marin",
  "Sao Tomé et Principe",
  "Arabie Saoudite",
  "Sénégal",
  "Serbie",
  "Les Seychelles",
  "Sierra Leone",
  "Singapour",
  "Saint-Martin",
  "Slovaquie",
  "Slovénie",
  "Îles Salomon",
  "Somalie",
  "Afrique du Sud",
  "Géorgie du Sud et îles Sandwich du Sud",
  "Soudan du sud",
  "Espagne",
  "Sri Lanka",
  "Soudan",
  "Surinam",
  "Svalbard et Jan Mayen",
  "Suède",
  "Suisse",
  "République arabe syrienne",
  "Taïwan",
  "Tadjikistan",
  "Tanzanie, République-Unie de",
  "Thaïlande",
  "Timor Oriental",
  "Aller",
  "Tokélaou",
  "Tonga",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turquie",
  "Turkménistan",
  "Îles Turques-et-Caïques",
  "Tuvalu",
  "Ouganda",
  "Ukraine",
  "Emirats Arabes Unis",
  "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
  "Îles mineures éloignées des États-Unis",
  "Les États-Unis d'Amérique",
  "Uruguay",
  "Ouzbékistan",
  "Vanuatu",
  "Venezuela (République bolivarienne du)",
  "Vietnam",
  "Îles Vierges (britanniques)",
  "Îles Vierges (États-Unis)",
  "Wallis et Futuna",
  "Sahara occidental",
  "Yémen",
  "Zambie",
  "Zimbabwe",
  "Iles Aland",
];
